### ISSUE TITLE
Apple-Up Arrow file and folder highlighting bugs that should not occur

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#576] opened 2021-10-01 22:59 UTC
**Describe the bug**
The following are Apple-Up Arrow file and folder highlighting bugs that should not occur.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha36-en_800k.2mg" disk image.
2. Double-click and open the "A2.Desktop" volume.
3. Double-click and open the "Desk.Acc" folder.
4. Double-click and open the "Control.Panels" folder.
5. Move the "Control.Panels" window to the lower right corner of the computer screen so that only the "Date" control panel is visible. Make sure that there is no window or part of a window is below and covered by the "Control.Panels" window.
5. Select the "Date" control panel.
6. Press Apple-Up Arrow.
7. The "Desk.Acc" window is activated and the "Control.Panels" folder in the "Desk.Acc" window is correctly highlighted.
8. The "Date" control panel in the "Control.Panels" window is incorrectly still highlighted.
9. Press Apple-Up Arrow.
10. The "A2.Desktop" window is activated and the "Desk.Acc" folder in the "A2.Desktop" window is correctly highlighted.
11. Select the "Desk.Acc" window.
12. The "Control.Panels" folder in the "Desk.Acc" window is incorrectly still highlighted.

**Expected behavior**
The preceding Apple-Up Arrow file and folder highlighting bugs should not occur.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 36 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment] 2021-10-01 23:27
Between step 10 and step 11, the "A2.Desktop" volume icon is incorrectly briefly highlighted before the "Desk.Acc" folder in the "A2.Desktop" window is correctly highlighted. Please fix this bug, too.

**Comment by inexorabletash** [comment] 2021-10-02 01:18
Duplicate of #566, already fixed.

**Closed by inexorabletash** 2021-10-02 01:18 UTC
Labels: bug, DeskTop

**Comment by c0mmander8** [comment] 2021-10-02 01:28
What about my second comment? My second comment is as follows:


Between step 10 and step 11, the "A2.Desktop" volume icon is incorrectly briefly highlighted before the "Desk.Acc" folder in the "A2.Desktop" window is correctly highlighted. Please fix this bug, too.

**Comment by c0mmander8** [comment] 2021-10-02 01:32
My second comment is not a lingering selection in an inactive window that is not cleared bug.

**Comment by c0mmander8** [comment] 2021-10-02 01:35
My second comment is not a duplicate issue of issue #566. Issue #566 could not have fixed it.

**Comment by inexorabletash** [comment] 2021-10-02 01:41
Please don't repeat yourself writing the same thing 3 times and adding noise.

There's actually a deeper bug there that I'm already looking at:

![image](https://user-images.githubusercontent.com/771547/135699933-edd4cc01-eb1b-4787-be96-6ac95506d5f3.png)

**Comment by c0mmander8** [comment] 2021-10-02 01:43
Thank you for your response.
