### ISSUE TITLE
The volume info header of a window or multiple windows is / are garbled when the window or multiple windows is / are restored

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#393] opened 2021-02-06 20:12 UTC
**Describe the bug**
The volume info header of a window or multiple windows is / are garbled when the window or multiple windows is / are restored.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open a window or multiple windows.
3. Quit Apple II DeskTop.
4. Restart Apple II DeskTop.
5. The volume info header of the window or multiple windows is / are garbled.

**Expected behavior**
The volume info header of a window or multiple windows should not be garbled when the window or multiple windows is / are restored.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 25 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment] 2021-02-07 02:22
Opening folders from the Apple menu and restoring windows go through the same code path (opening a window from a path), so whatever you're running into is likely a duplicate of #392.

_"window or multiple windows is / are garbled"_ - please don't write like this, it's very irritating. It is not readable English and is extraneous detail at best. Be succinct in issue titles.

**Comment by c0mmander8** [comment] 2021-02-07 02:36
In this issue, a different part of the volume info header is garbled than in issue #392. This issue is not a duplicate issue of issue #392.

**Comment by c0mmander8** [comment] 2021-02-07 04:42
Please reopen this issue so that, as referenced above, the volume info header of a window or multiple windows should not be garbled when the window or multiple windows is / are restored.

**Comment by inexorabletash** [comment] 2021-02-07 06:03
Screenshots or STFU

**Comment by inexorabletash** [comment] 2021-02-09 03:50
Sorry. That was quite rude of me. 

I appreciate your attention to detail. Bear in mind that "duplicate" is usually referring to the same root cause. In this case, given your issue description, the repro steps, and my understanding of the code, it's almost certainly the same root cause. 

As noted previously, screenshots are very useful when debugging issues. I can provide instructions on how to create screenshots for whatever operating system or set of devices you have.

**Comment by c0mmander8** [comment] 2021-02-23 09:31
The garbling mentioned in this issue is that when you restore a window or multiple windows, the volume info header of each window says "2 Items" if there is only one volume mounted, no matter how many items there are in the windows. The volume info header of each window says "3 Items" instead if there are two volumes mounted. The volume info header of each window says "4 Items" instead if there are three volumes mounted.

**Comment by inexorabletash** [comment] 2021-02-26 01:42
Thanks. Another person reported the issue and supplied a screenshot which also showed the "garbling"; the repro for that is to partially cover then uncover one of the restored windows; the repaint would have the correct count, but it might only be partially painted.

**Closed** 2021-02-26 01:43 UTC
Labels: DeskTop, bug
