### ISSUE TITLE
GSplus freezes when using two disks with the identical ProDOS volume name in Apple II DeskTop

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#310] opened 2020-12-01 17:30 UTC
GSplus v0.14 (the latest version of the program) freezes when using two disks with the identical ProDOS volume name (not the identical file name in the emulator) in Apple II DeskTop 1.2 (Pre-)Alpha 22 (the latest version of the program) on Windows.

**Comment by c0mmander8** [comment] 2020-12-01 17:30
This issue is not related to issue #309. This is a totally unrelated issue.

**Comment by c0mmander8** [comment] 2020-12-01 17:56
This occurs when selecting file-or disk-related functions from the menu bar. Also, certain desk accessories, but not all of them, do not work in this scenario.

**Comment by c0mmander8** [comment] 2020-12-01 18:02
This issue occurs when selecting file-or disk-related functions from the menu bar. Also, certain desk accessories, but not all of them, do not work in this scenario.

**Comment by c0mmander8** [comment] 2020-12-01 18:13
The desk accessories don't freeze though.

**Comment by c0mmander8** [comment] 2020-12-01 18:19
The desk accessories do not freeze though.

**Comment by c0mmander8** [comment] 2020-12-01 18:52
As referenced in issue #311 and issue #312, the desk accessories situation is actually totally unrelated to this scenario.

**Comment by c0mmander8** [comment] 2020-12-01 19:13
As referenced in issue #311 and issue #312, the desk accessories situation is actually totally unrelated to this issue.

**Comment by c0mmander8** [comment] 2020-12-02 01:04
I take my last comments back. I think that the desk accessories situation as referenced in issue #311 and issue #312 is in fact related to this issue.

**Comment by inexorabletash** [comment] 2020-12-02 01:10
Please don't make redundant comments (e.g. to restate the same sentence with "issue" instead of "scenario"). It is confusing and time consuming to read, and takes time away from useful work.

I can't reproduce this problem. I assigned disks with the same name to s6d1 and s6d2 in GSplus and DeskTop started correctly, I was able to select the icons, etc.

Can you be more specific? When do you observe DeskTop freezing - at startup or later? Is the duplicate volume name the same as the one containing DeskTop, or other volumes? Did you try reproducing this in other emulators, e.g. AppleWin?

Screen shots (you can paste images into GitHub) are extremely useful, as they often capture details you may not think to include (e.g. what volumes you have)

**Comment by c0mmander8** [comment] 2020-12-02 03:07
I can no longer reproduce this problem. I assigned the two disks with the identical ProDOS volume name (not the identical file name in the emulator) to s7d1 and s7d2 in GSplus. The duplicate volume name actually belongs to a total duplicate of the volume containing Apple II DeskTop. There must be some serious file corruption going on. Apple II DeskTop started correctly. No freezes ever happened at startup. No freezes happen anymore when selecting File > Copy a File..., File > Delete a File..., Special > Format a Disk... and Special > Erase a Disk... respectively and canceling out of the resulting dialog boxes. But issue #311 and issue #312 still occur with the Find Files and Run Basic Here desk accessories. I replaced my copy of Apple II DeskTop earlier but it did not help the situation. I replaced my copy of Apple II DeskTop again just now and the freezes are now gone. I did not try reproducing this in other emulators, though. Sorry, I am unable to provide any screenshots.

**Comment by inexorabletash** [comment] 2020-12-02 04:44
FWIW, DeskTop is supposed to report an error on startup if there are duplicate volume names, I'm not sure why that's not happening. Having duplicate volume names is going to make ProDOS very confused, so that needs to be avoided. If an attempt is made to access `/HD/A2.DESKTOP/DESK.ACC/FIND.FILES` and there are two possible disks then ProDOS can issue a Duplicate Volume error, I'm not sure DeskTop handles that everywhere it might need to.

Corruption might have happened when you were testing Disk Copy or Format a Disk. Disk Copy in particular was really buggy due to some glitches that snuck into disassembly (some pointers were wrong!) and just generally both of those issued block-level commands that could have been corrupted by the bugs we've been investigating. I was just seeing corruption in the disk image I always use for development a few minutes ago - fortunately I've got backups of the image. Now might be a good time to switch to a backup copy of your main image, if you've got one.

I'll close this out but keep an eye out.

**Closed by inexorabletash** 2020-12-02 04:44 UTC

**Comment by c0mmander8** [comment] 2020-12-02 04:56
You were right about the desk accessories situation with the Find Files and Run Basic Here desk accessories not working, as referenced in issue #311 and issue #312. I did not have a window open in each case. Thank you.

**Comment by I3arana** [comment] 2020-12-02 10:35
Ive had Duplicate 32mAeg images and DeskTop didnt report any errors. No prodos passed on errors either.
