### ISSUE TITLE
GS/OS (ProDOS 2.5.x) or AppleWorks filename casing is not applied to a renamed file, folder or volume that has GS/OS (ProDOS 2.5.x) or AppleWorks filename casing until the the respective window containing the file or folder or the desktop containing the volume is refreshed

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#622] opened 2022-01-13 19:06 UTC
**Describe the bug**
GS/OS (ProDOS 2.5.x) or AppleWorks filename casing is not applied to a renamed file, folder or volume that has GS/OS (ProDOS 2.5.x) or AppleWorks filename casing until the the respective window containing the file or folder or the desktop containing the volume is refreshed.

**To Reproduce**
1. Start Apple II DeskTop from "A2.Desktop", which is a fresh copy of the "A2DeskTop-1.2-alpha40-en_800k.2mg" disk image, with a fresh copy of "Live.Install" mounted, which is a fresh copy of the "Live.Install.po" disk image from ftp://ftp.apple.asimov.net/pub/apple_II/images/gs/os/gsos/Apple_IIGS_System_6.0.4/.
2. Double-click and open the "Live.Install" volume, which has GS/OS (ProDOS 2.5.x) filename casing applied.
3. Click on and select the "synthLAB" application program with GS/OS (ProDOS 2.5.x) filename casing applied.
4. Click on the File menu and go to File > Rename....
5. Type a lowercase letter "a" so that the "New name:" text field states "synthLABa".
6. Click OK.
7. The "synthLAB" application program clicked on and selected in step 3 now reads as "Synthlaba" with GS/OS (ProDOS 2.5.x) filename casing no longer applied.
8. Click on and select the "AppleTalk" folder with GS/OS (ProDOS 2.5.x) filename casing applied.
9. Click on the File menu and go to File > Rename....
10. Type a lowercase letter "a" so that the "New name:" text field states "AppleTalka".
11. Click OK.
12. The "AppleTalk" folder clicked on and selected in step 8 now reads as "Appletalka" with GS/OS (ProDOS 2.5.x) filename casing no longer applied.
13. Click on and select the "BASIC.System" application program with GS/OS (ProDOS 2.5.x) filename casing applied.
14. Click on the File menu and go to File > Rename....
15. Type a lowercase letter "a" so that the "New name:" text field states "BASIC.Systema".
16. Click OK.
17. The "Live.Install" window is refreshed.
18. The "BASIC.System" application program clicked on and selected in step 13 now reads as "BASIC.SystemA" with GS/OS (ProDOS 2.5.x) filename still applied.
19. The "synthLAB" application program clicked on and selected in step 3 now reads as "synthLABA" with GS/OS (ProDOS 2.5.x) filename casing once again applied.
20. The "AppleTalk" folder clicked on and selected in step 8 now reads as "AppleTalkA" with GS/OS (ProDOS 2.5.x) filename casing once again applied.
21. Click on and select the "Live.Install" volume, which has GS/OS (ProDOS 2.5.x) filename casing applied.
22. Click on the File menu and go to File > Rename....
23. Type a lowercase letter "a" so that the "New name:" text field states "Live.Installa".
24. Click OK.
25. The "Live.Install" volume clicked on and selected in step 21 now reads as "Live.Installa" with GS/OS (ProDOS 2.5.x) filename casing no longer applied.
26. Make sure that the "Live.Install" volume clicked on and selected in step 21, now reading as "Live.Installa" with GS/OS (ProDOS 2.5.x) filename casing no longer applied, is still selected.
27. Click on the Special menu and go to Special > Check Drive.
28. The "Live.Install" volume clicked on and selected in step 21, now reading as "Live.Installa" with GS/OS (ProDOS 2.5.x) filename casing no longer applied, is refreshed.
29. The "Live.Install" volume clicked on and selected in step 21 now reads as "Live.InstallA" with GS/OS (ProDOS 2.5.x) filename casing once again applied.

**Expected behavior**
GS/OS (ProDOS 2.5.x) or AppleWorks filename casing should be applied to a renamed file, folder or volume that has GS/OS (ProDOS 2.5.x) or AppleWorks filename casing immediately.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 40 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment] 2022-01-13 19:17
As referenced in issue #612, please do not ban me for my long issue title for this issue. I am trying to be helpful. I find it extremely hard to shorten my long issue titles. Could you please shorten my long issue title for this issue for me?

**Comment by inexorabletash** [comment] 2022-01-15 17:03
This is effectively a duplicate of #352; marking as a duplicate to declutter the issue tracker.

**Closed by inexorabletash** 2022-01-15 17:03 UTC
Labels: duplicate, bug, DeskTop
