### ISSUE TITLE
The menu bar clock in the Apple II DeskTop app does not update the time for a few seconds after exiting either the Invert or the Matrix screen savers

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#657] opened 2022-02-19 11:36 UTC
**Describe the bug**
The menu bar clock in the Apple II DeskTop app does not update the time for a few seconds after exiting either the Invert or the Matrix screen savers.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open the Invert screen saver or the Matrix screen saver.
3. Wait a few minutes.
4. Exit the screen saver.
5. The menu bar clock does not update the time for a few seconds.

**Expected behavior**
The menu bar clock in the Apple II DeskTop app should update the time immediately and instantaneously after exiting either the Invert or the Matrix screen savers.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 41 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by inexorabletash** [comment] 2022-02-19 17:19
Duplicate of #646

**Closed by inexorabletash** 2022-02-19 17:19 UTC
Labels: bug, DeskTop

**Comment by inexorabletash** [comment] 2022-02-19 17:21
Or #589 depending on whether the complaint is about the clock appearing, or the time being a few seconds behind. Either way, duplicate.

**Comment by c0mmander8** [comment] 2022-02-19 18:08
Please reopen this issue. This issue is not a duplicate issue of either issue #589 or issue #646. The time and the day of the week displayed on the menu bar clock when you exit the Invert screen saver or exit the Matrix screen saver is the time and the day of the week when you first opened the Invert screen saver or first opened the Matrix screen saver. The time and the day of the week displayed on the menu bar clock when you exit the Invert screen saver or exit the Matrix screen saver can be many many minutes, multiple hours and even days behind the current time and the current day of the week depending on when you first opened the Invert screen saver or first opened the Matrix screen saver. It then takes a few seconds for the time and the day of the week displayed on the menu bar clock to be updated to the current time and the current day of the week. The time and the day of the week displayed on the menu bar clock when you exit the Invert screen saver or exit the Matrix screen saver should immediately and instantaneously be updated to the current time and the current day of the week.

**Comment by inexorabletash** [comment] 2022-02-19 18:33
The fix for #646 in cd229f0e2 forces a clock refresh when the DA exits, so it's already taken care of.
