### ISSUE TITLE
Windows should be restored after launching and then quitting Disk Copy

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#435] opened 2021-03-20 23:42 UTC
**Describe the bug**
Windows are not restored after launching and then quitting Disk Copy.

**To Reproduce**
1. Start Apple II DeskTop.
2. Open multiple windows.
3. Launch Disk Copy.
4. Quit Disk Copy.
5. The windows are not restored.

**Expected behavior**
Windows should be restored after launching and then quitting Disk Copy.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 Alpha 27 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
There is no other context about the problem here.

**Comment by c0mmander8** [comment] 2021-03-20 23:48
I think this issue is related to issue #434.

**Comment by inexorabletash** [comment] 2021-03-20 23:54
Duplicate of #434 - it's just "restoring" zero windows.

**Closed** 2021-03-20 23:54 UTC
Labels: DeskTop, bug, duplicate
