### ISSUE TITLE
GS/OS (ProDOS 2.5.x) files and folders lose their correct filename casing when copied or moved

### ISSUE THREAD

**Issue by c0mmander8** [a2stuff/a2d#383] opened 2021-01-20 05:33 UTC
**Describe the bug**
GS/OS (ProDOS 2.5.x) files and folders lose their correct filename casing when copied or moved. They revert to having the standard Apple II DeskTop filename casing applied. I do not know whether or not this bug also applies to AppleWorks filename casing, but suspect so.

**To Reproduce**
1. Start Apple II DeskTop.
2. Select a file or a folder with GS/OS (ProDOS 2.5.x) filename casing.
3. Copy or move that file or that folder to another window.
4. If copied, the copy of the file or the copy of the folder has the standard Apple II DeskTop filename casing applied instead of GS/OS (ProDOS 2.5.x) filename casing applied.
5. If moved, the file or the folder now has the standard Apple II DeskTop filename casing applied instead of GS/OS (ProDOS 2.5.x) filename casing applied.

**Expected behavior**
GS/OS (ProDOS 2.5.x) files and folders should not lose their correct filename casing when copied or moved. They should not revert to having the standard Apple II DeskTop filename casing applied. If applicable, AppleWorks files should not also lose their correct filename casing when copied or moved. They should not also revert to having the standard Apple II DeskTop filename casing applied.

**Screenshots**
I am sorry. I have no screenshots to help explain my problem.

**System Details (please complete the following information):**
 - System [e.g. Apple IIe Enhanced, Apple IIc, Apple IIgs] Apple IIGS (ROM 01)
 - Emulator? [e.g. real hardware, or emulator name] GSplus 0.14 (the latest version of the program)
 - ProDOS version ProDOS 2.4.2 (the latest version)
 - DeskTop version (from About > Apple II DeskTop...) Apple II DeskTop 1.2 (Pre-)Alpha 24 (the latest version of the program)
 - Other [e.g. mouse, memory expansions, disk types, etc]

**Additional context**
I do not know whether or not this bug also applies to AppleWorks filename casing, but suspect so.

**Comment by inexorabletash** [comment] 2021-01-22 05:51
Duplicate of #352

**Closed by inexorabletash** 2021-01-22 05:51 UTC
Labels: DeskTop, bug
