### ISSUE TITLE
Pressing arrow keys in file windows doesn't move selection as expected

### ISSUE THREAD

**Issue by xandark** [a2stuff/a2d#748] opened 2023-03-05 03:04 UTC
Depending on the view mode of a window (icons or list), pressing the arrow key to move the selection to the next icon does not move spatially, but rather in list order. 

For example, in the large icon view, pressing up and down arrow keys moves the selection to the left or right.

In list view, pressing left and right arrow keys mimic the up and down arrow keys. 

If spatially-aware cursor selection is too much to implement, then maybe a short-term solution would be to only allow left/right presses for the icon/small icon view modes, and only the up/down presses for the list view mode.

**Comment by inexorabletash** [comment] 2023-03-05 03:06
Duplicate of #300

**Closed by inexorabletash** 2023-03-05 03:06 UTC
Labels: bug, DeskTop
